### ISSUE TITLE
Feature request: input with aria-describedby and title

### ISSUE THREAD

**Issue by barabba9174** [russmaxdesign/accessible-forms#2]
Hi, in this example https://russmaxdesign.github.io/accessible-forms/accessible-name-input04.html you are describing the behaviour by adding the title, that is announced as description.
Can you provide also the example with title and aria-describedby?

BTW: thank you for your repo, it was long time that I was try to find something like this!

**Comment by russmaxdesign** [comment]
@barabba9174 Apologies for the slow response. Two new tests added:

https://russmaxdesign.github.io/accessible-forms/input-error-message-title.html

https://russmaxdesign.github.io/accessible-forms/input-error-message-title-aria-describedby.html
